/*
export const SAY_HELLO = 'SAY_HELLO'

export const SELECT_BOOK = 'SELECT_BOOK'
export const INVALIDATE_BOOK = 'INVALIDATE_BOOK'

export const REQUEST_NOTES = 'REQUEST_NOTES'
export const RECEIVE_NOTES = 'RECEIVE_NOTES'

export const SAY_HELLO_ASYNC_REQUEST = 'SAY_HELLO_ASYNC_REQUEST'
export const SAY_HELLO_ASYNC_SUCCESS = 'SAY_HELLO_ASYNC_SUCCESS'
export const SAY_HELLO_ASYNC_FAILURE = 'SAY_HELLO_ASYNC_FAILURE'
*/
